[package]
name = "benchmarks"
version = "0.2.0"
edition = "2024"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "clone"
harness = false

[[bench]]
name = "convert"
harness = false

[dependencies]
flexrc = { path = "../flexrc", features = ["track_threads"] }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
